{% set name = "amst2" %}
{% set version = "0.3.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

requirements:
  host:
    - python
    - numpy
    - h5py
    - tifffile
    - ruamel.yaml
    - squirrel>=0.3.0
  run:
    - python
    - numpy
    - h5py
    - tifffile
    - ruamel.yaml
    - squirrel>=0.3.0

test:
  imports:
    - AMST2
  commands:
    - python -m unittest discover -s test

about:
  home: https://github.com/jhennies/amst2.git
  license: GPLv3
  license_family: GPL
  summary: Alignment to median smoothed template workflow

extra:
  recipe-maintainers:
    - jhennies
