# This is an example parameter file for the nth-slice-by-slice pre-alignment workflow
# Copy this parameter file to your desired location and adjust to your needs
# Then run the workflow using:
#    amst-nsbs-pre-align /path/to/my/params-nsbs-pre-align.yaml
# This parameter file has been tested on the first 32 slices of the https://www.ebi.ac.uk/empiar/EMPIAR-10311/ dataset

general:
  input_dirpath: /path/to/your/data(.ome.zarr)  # tif stack or ome-zarr dataset
  output_dirpath: /path/to/target/directory
  auto_pad: true  # This will make sure the canvas size is nicely adjusted to the data
  cores: 16
  batch_size: 8
  max_cores_per_task: 8

stack_to_ome_zarr:
  # If the input directory does not have an ome-zarr extension (*.ome.zarr or *.OME.ZARR),
  # it is assumed to be a tif stack and the conversion to ome-zarr will be performed.
  # Set to 'active: false' to treat the input directory as ome.zarr data regardless of it's extension
  active: true
  resolution: [0.008, 0.005, 0.005]  # Adjust the resolution and unit below to your dataset!
  unit: micrometer

sbs_alignment:
  auto_mask: non-zero  # non-zero or variance
  gaussian_sigma: 2.0
  initialize_offsets_method: init_elx
  initialize_offset_kwargs: ["binning:32", "spacing:256", "elx_binning:4", "elx_max_iters:32", "mi_thresh:-0.8"]
  elx_number_of_resolutions: 2  # Increase for bigger initial jumps, if not using init_elx above
  elx_number_of_spatial_samples: 2048  # Increase for large images
  elx_maximum_number_of_iterations: 256  # Increase for finer alignment
  preview_downsample_level: 2

nsbs_alignment:
  z_step: 8  # Adjust the z-step if needed
  auto_mask: non-zero
  gaussian_sigma: 2.0
  preview_downsample_level: 2

apply_pre_align: {}

pre_align_to_tif_stack:
  active: true
