# This is an example parameter file for the AMST workflow
# Copy this parameter file to your desired location and adjust to your needs
# Then run the workflow using:
#    amst2-wf-amst-run /path/to/my/params-amst-bspline-slurm.yaml

general:
  # These three can be omitted if AMST is run inside the same target folder as the pre-align >>>
  input_dirpath: /path/to/the/raw-data.ome.zarr  # Defaults to <output_dirpath>/stack_to_ome_zarr/input-raw.ome.zarr
  pre_align_dirpath: /path/to/your/pre-alignment.ome.zarr  # Defaults to <output_dirpath>/apply_pre_align/nsbs-pre-align.ome.zarr
  pre_align_transforms: /path/to/pre-alignment-transforms.json  # Defaults to <output_dirpath>/nsbs-pre-align.json
  # <<<run
  output_dirpath: /path/to/target/directory
  stack_key: s0
  stack_pattern: '*.tif'
  cluster: slurm
  batch_size: 16
  cores: 2048
  max_cores_per_task: 16

amst:
  elastix_parameter_file: auto
  transform: bspline
  median_radius: 7
  gaussian_sigma: 2.0
  auto_mask_off: false
  mem:
    apply_final_transformations:16000

apply_amst:
  mem:
    apply_final_transform: 16000

amst_to_tif_stack:
  active: false
